baseurl = "http://derzoelli.github.com"
title = "robinzoellner"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  author = "Robin Zoellner"
  info = "Hey! I'm Robin and you can find me here:"
  description = "Robin's personal website"
  keywords = "blog,developer,personal"
  gravatar = "mail@robinzoellner.com"
  since = 2022

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"


  colorScheme = "auto"
  hidecolorschemetoggle = false

  # Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 3
  url = "https://github.com/derzoelli/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 1
  url = "https://twitter.com/robinzoellner/"
  [[params.social]]
  name = "Insta"
  icon = "fa fa-instagram fa-2x"
  weight = 2
  url = "https://www.instagram.com/robinzoellner/"
  [[params.social]]
  name = "Spotify"
  icon = "fa fa-spotify fa-2x"
  weight = 4
  url = "https://open.spotify.com/user/robinzoellner?si=a0b6621e2d024b6c"
  [[params.social]]
  name = "Mail"
  icon = "fa fa-envelope-o fa-2x"
  weight = 5
  url = "mailto:mail@robinzoellner.com"
  